---
- name: Echo AWX params
  hosts: "{{ event_data['CMDBName'] | default((event_data['NodeAlias']) | default('none')) }}"
  gather_facts: false

  # pre_tasks:
  #   - name: "Debug the event_data and user_args"
  #     ansible.builtin.debug:
  #       msg: |
  #         {
  #           "summary": "Echoed the input",
  #           "hostname": "{{ event_data }}",
  #         }
  #     delegate_to: localhost
  #     run_once: true
      
  tasks:
    - name: "SOfA AWX Results"
    # Echo event_data and user_args sub elements of extra_vars param"
      ansible.builtin.debug:
        msg: |
          {
            "summary": "Echoed the input",
            "hostname": "{{ event_data['CMDBName'] | default((event_data['NodeAlias'] | default('none')) }}",
            "ip": "{{ inventory_hostname }}",
            "exit_code": 10,
            "success": true,
            "successOutput": "Success! event_data:\n{{ event_data }}\n\nuser_args:\n{{user_args}}",
            "failureOutput": "Fail! event_data:\n{{ event_data }}\n\nuser_args:\n{{user_args | default({}) }}",
          }          
          

