---
- name: Echo AWX params
  hosts: "{{ trap_details['NodeAlias'] | default((trap_details['nodealias']) | default('none')) }}"
  gather_facts: false

  tasks:
    - name: "SOfA AWX Results"
    # Echo trap_details sub element of extra_vars param"
      ansible.builtin.debug:
      msg: |
        {
          "summary": "Echoed the input",
          "hostname": "{{ trap.cmdbname }}",
          "ip": "{{ device }}",
          "interface": "{{ NodeAlias }}",
          "status": "Success",
          "finalOutput": "{{ trap_details }}"
        }          
          

