---
- name: Echo AWX params
  hosts: "{{ trap_details['NodeAlias'] | default((trap_details['nodealias']) | default('all') }}"
  gather_facts: false

  tasks:
    - name: Echo args sub element of extra_vars param
      ansible.builtin.debug:
        msg: 
          - "{{ trap_details }}"
          - "{{ trap_details | type_debug }}"
          - "{{ trap_details.keys() | list }}"
          #- "{{ trap_details['NodeAlias'] }}"
          - "{{ trap_details['NodeAlias'] | default((trap_details['nodealias']) | default() }}"
          

