---
- name: Echo AWX params
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Echo Extra Parameters
      ansible.builtin.debug:
        msg: "{{ extra_vars_dict }}"
      vars:
        extra_vars_dict: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS', default='{}') | from_json }}"
    - name: Echo Raw EXTRA_VARS Value
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS', default='No extra vars provided') }}"
