---
- name: Echo AWX params
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Echo 
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS') | default('{}') | from_json }}"
