---
- name: Echo AWX params
  hosts: "{{ trap_details['NodeAlias'] | default((trap_details['nodealias']) | default('none')) }}"
  gather_facts: false

  tasks:
    - name: "CMDOUT - Echo trap_details sub element of extra_vars param"
      ansible.builtin.debug:
        msg: 
          - "{{ trap_details }}"
          

