---
- name: Echo AWX params
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Echo Extra Parameters
      ansible.builtin.debug:
        msg: "{{ extra_params }}"
      vars:
        extra_params: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS') | default('{}', true) | from_json }}"
