---
- name: Echo AWX params
  hosts: "{{ device|default(all) }}"
  gather_facts: false

  tasks:
    - name: Echo args sub element of extra_vars param
      ansible.builtin.debug:
        msg: "{{ trap_details }}"

