---
- name: Ping 
  hosts: "all"
  gather_facts: false

  # pre_tasks:
  #   - name: "Debug the event_data and user_args"
  #     ansible.builtin.debug:
  #       msg: |
  #         {
  #           "summary": "Echoed the input",
  #           "hostname": "{{ event_data }}",
  #         }
  #     delegate_to: localhost
  #     run_once: true
      
  tasks:
    - name: "TASK - Ping the host - Linux"
      ansible.builtin.ping:
        data: "pinging"
      register: ssh_ping_result
      when: ansible_connection != "winrm"
      ignore_errors: true
      ignore_unreachable: true

    - name: "Debug - ping the host - Linux"
      debug:
        msg: 
          - "{{ ssh_ping_result }}"
      ignore_errors: true

    - name: "TASK - Ping the host - Windows"
      ansible.windows.win_ping:
        data: "pinging"
      register: win_ping_result
      when: ansible_connection == "winrm"
      ignore_errors: true
      ignore_unreachable: true

    - name: "TASK - Rename the ping result"
      set_fact:
        ping_result: "{{ ssh_ping_result }}"
      when: 
        - ssh_ping_result is defined
        - ssh_ping_result.skipped is not defined
      ignore_errors: true

    - name: "TASK - Rename the win_ping result"
      set_fact:
        ping_result: "{{ win_ping_result }}"
      when: 
        - win_ping_result is defined
        - win_ping_result.skipped is not defined
      ignore_errors: true

    - name: "TASK - Create success message"
      set_fact: 
        ping_output: |
            "summary": "Ping: Success",
            "hostname": "{{ event_data['cmdbname'] | default((event_data['CmdbName']) | default(inventory_hostname)) }}",
            "ip": "{{ inventory_hostname }}",
            "exit_code": 10,
            "success": true,
            "successOutput": "Success! {{ ping_result }}",
            "failureOutput": "N/A",
      when: 
        - ping_result is defined
        - (ping_result.unreachable is not defined or not ping_result.unreachable)

    - name: "TASK - Create failure message"
      set_fact: 
        ping_output: |
            "summary": "Ping: Failure",
            "hostname": "{{ event_data['cmdbname'] | default((event_data['CmdbName']) | default(inventory_hostname)) }}",
            "ip": "{{ inventory_hostname }}",
            "exit_code": 0,
            "success": false,
            "successOutput": "N/A",
            "failureOutput": "Failure: {{ ping_result }}",
      when:
        - ping_result is defined
        - (ping_result.unreachable is defined and ping_result.unreachable)
          

    - name: "SOfA AWX Results"
      ansible.builtin.debug:
        msg: | 
          {
            {{ ping_output }}
          }