---
- name: Ping 
  hosts: "all"
  gather_facts: false

  # pre_tasks:
  #   - name: "Debug the event_data and user_args"
  #     ansible.builtin.debug:
  #       msg: |
  #         {
  #           "summary": "Echoed the input",
  #           "hostname": "{{ event_data }}",
  #         }
  #     delegate_to: localhost
  #     run_once: true
      
  tasks:
    - name: "Ping the host - Linux"
      ansible.builtin.ping:
        data: "pinging"
      register: ssh_ping_result
      when: ansible_connection != "winrm"
      ignore_errors: true

    - name: "Ping the host - Windows"
      ansible.windows.win_ping:
        win_ping:
      register: win_ping_result
      when: ansible_connection == "winrm"
      ignore_errors: true

    - name: "Combine the ping results"
      set_fact:
        ping_result: "{{ssh_ping_result | default(win_ping_result | default('')) }}"
      when: ssh_ping_result is defined or win_ping_result is defined
      ignore_errors: true

    - name: "SOfA AWX Results"
      ansible.builtin.debug:
        msg: |
          {
            "summary": "Pinged the host successfully",
            "hostname": "{{ event_data['cmdbname'] | default((event_data['CmdbName']) | default('none')) }}",
            "ip": "{{ inventory_hostname }}",
            "exit_code": 10,
            "success": true,
            "successOutput": "Success! {{ ping_result }}",
            "failureOutput": "N/A",
          }
      when: 
        - ping_result is defined
        - (ping_result.unreachable is not defined or not ping_result.unreachable)

    - name: "SOfA AWX Results"
    # Echo event_data and user_args sub elements of extra_vars param"
      ansible.builtin.debug:
        msg: |
          {
            "summary": "Pinged the host failed",
            "hostname": "{{ event_data['cmdbname'] | default((event_data['CmdbName']) | default('none')) }}",
            "ip": "{{ inventory_hostname }}",
            "exit_code": 0,
            "success": false,
            "successOutput": "N/A",
            "failureOutput": "Failure: {{ ping_result }}",
          }
      when:
        - ping_result is defined
        - (ping_result.unreachable is defined and ping_result.unreachable)
          

